// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.906
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Footer() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<footer class=\"w-full bg-slate-800 text-slate-200 px-5 py-8 mt-0\"><div class=\"max-w-4xl mx-auto flex gap-y-8 flex-wrap md:flex-nowrap\"><div class=\"flex flex-col md:w-1/2 md:mr-auto\"><h1 class=\"text-lg font-medium mb-8\">Michael Miranda</h1><p class=\"text-lg\">Congratulations on scrolling all the way down! If you want to stay in touch, follow me on <a href=\"https://twitter.com/mrpineapples24\" class=\"text-blue-500\">Twitter</a>!</p></div><div class=\"flex w-full md:w-auto md:gap-x-40\"><div class=\"flex flex-col w-1/2\"><h1 class=\"text-lg text-pink-400 font-medium mb-8\">Social</h1><ul class=\"flex flex-col gap-y-4 text-blue-500\"><li><a href=\"https://github.com/mrpineapples\">Github</a></li><li><a href=\"https://linkedin.com/in/michaelmiranda18/\">LinkedIn</a></li><li><a href=\"https://twitter.com/mrpineapples24\">Twitter</a></li></ul></div><div class=\"flex flex-col w-1/2\"><h1 class=\"text-lg text-pink-400 font-medium mb-8\">Links</h1><ul class=\"flex flex-col gap-y-4 text-blue-500\"><li><a href=\"/\">Home</a></li><li><a href=\"/blog\">Blog</a></li><li><a href=\"/about\">About</a></li><li><a href=\"/contact\">Contact</a></li></ul></div></div></div></footer>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
